### ISSUE TITLE
Try to use

### ISSUE THREAD

**Issue by pdtan** [Droeftoeter/pokapi#1]
Fatal error: Uncaught Pokapi\Exception\NoResponse in ...\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Service.php:103 Stack trace: #0 ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\API.php(82): Pokapi\Rpc\Service->batchExecute(Array, Object(Pokapi\Rpc\Position)) #1 ...\pkm\test.php(16): Pokapi\API->initialize() #2 {main} thrown in ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Service.php on line 103

require_once __DIR__ . '/vendor/autoload.php';
use Pokapi\Authentication\TrainersClub;
use Pokapi\API;
$authentication = new TrainersClub('xx', 'xx');
$api = new API($authentication, 21.029395, 105.853541, 10);

// Initializes like the real client
$api->initialize();

// Accept ToS
$api->acceptTerms();

// Execute operation
$getPlayerResponse = $api->getPlayerData();
$mapObjects = $api->getMapObjects();
var_dump($mapObjects);

**Comment by Droeftoeter** [comment]
It means you didn't get a response from the server, or an empty response. Do you continously get the same error? Or is it only every once in a while?

**Comment by pdtan** [comment]
I got this since I downloaded your code.

**Comment by Droeftoeter** [comment]
This should be fixed now. The request was being throttled. See [v1.0.1](https://github.com/Sjaakmoes/pokapi/releases/tag/v1.0.1)

**Comment by pdtan** [comment]
I don't know if I do wrong
Fatal error: Uncaught Pokapi\Exception\NoResponse: Request Exception in ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Service.php:113 Stack trace: #0 ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\API.php(82): Pokapi\Rpc\Service->batchExecute(Array, Object(Pokapi\Rpc\Position)) #1 ...\pkm\test.php(16): Pokapi\API->initialize() #2 {main} thrown in ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Service.php on line 113

**Comment by Droeftoeter** [comment]
@pdtan I've updated the master branch, did you use composer to install or did you get it from github? If you update the exception should provide more information in what's going wrong.

**Comment by pdtan** [comment]
http://i.imgur.com/MGW2TNK.png
If I don't modify, I will get

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ...\pkm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 ...\pkm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 ...\pkm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 ...\pkm\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 ...\pkm\vendor\guzzlehttp\guzzle\src\ in ...\pkm\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

But I modified: http://i.imgur.com/zFm81lG.png, I got
Fatal error: Uncaught Pokapi\Exception\NoResponse: Request Exception in ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Service.php:110 Stack trace: #0 ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\API.php(82): Pokapi\Rpc\Service->batchExecute(Array, Object(Pokapi\Rpc\Position)) #1 ...\pkm\test.php(16): Pokapi\API->initialize() #2 {main} thrown in ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Service.php on line 110

**Comment by Droeftoeter** [comment]
It should be fixed now.

**Comment by pdtan** [comment]
Ty for your detailed exceptions. I know where caused error.
But new error is coming ^^
Fatal error: Uncaught TypeError: Argument 1 passed to Protobuf\EnumCollection::add() must be an instance of Protobuf\Enum, integer given, called in ...\pkm\vendor\sjaakmoes\pokapi\POGOProtos\Data\PlayerData.php on line 780 and defined in ...\pkm\vendor\protobuf-php\protobuf\src\EnumCollection.php:28 Stack trace: #0 ...\pkm\vendor\sjaakmoes\pokapi\POGOProtos\Data\PlayerData.php(780): Protobuf\EnumCollection->add(0) #1 ...\pkm\vendor\sjaakmoes\pokapi\POGOProtos\Networking\Responses\GetPlayerResponse.php(257): POGOProtos\Data\PlayerData->readFrom(Object(Protobuf\ReadContext)) #2 ...\pkm\vendor\protobuf-php\protobuf\src\AbstractMessage.php(29): POGOProtos\Networking\Responses\GetPlayerResponse->readFrom(Object(Protobuf\ReadContext)) #3 ...\pkm\vendor\sjaakmoes\pokapi\src\Pokapi\Rpc\Requests\GetPlayer.php(41): Protobuf\AbstractMessage->__construct('\x08\x01\x12I\x08\xB7\x85\xDB\xE7\xDF*\x12\tLi...') #4 D:\VertrigoServ64\ in ...\pkm\vendor\protobuf-php\protobuf\src\EnumCollection.php on line 28

**Comment by Droeftoeter** [comment]
Seems like a bug in the protobufs. I'll pick that up later. You don't really need `$getPlayerResponse = $api->getPlayerData();` to fetch map objects. Added an issue for this #2

**Comment by pdtan** [comment]
Fixed by modify:
$this->tutorial_state->add($reader->readVarint($stream));
to
$this->tutorial_state->add(\POGOProtos\Enums\TutorialState::valueOf($reader->readVarint($stream)));

But seems get empty map objects like api of NicklasWallgren

**Comment by Droeftoeter** [comment]
@pdtan Maybe you're scanning an empty area? I'm using it and it finds pokemon. But you need to scan more areas.

**Comment by pdtan** [comment]
same area, on python, it displays pokestop

**Comment by Droeftoeter** [comment]
Should be resolved.
